site_name: thecrbox
repo_url: https://github.com/thecrbox/docs
repo_name: docs
site_url: https://thecrbox.github.io
theme:
    name: material
    custom_dir: overrides

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - markdown_include.include:
      base_path: docs

plugins:
  - mkdocs-video
  - search
  - autorefs

extra_javascript:
  - javascripts/improv-loader.js

nav:
  - Home: index.md
  - Manual:
    - User interface:
      - Overview: ui.md
    - Wi-Fi provisioning:
      - Overview: provisioning.md
      - Provisioning with Android: provisioning/provisioning-android.md
      - Provisioning with iPhone: provisioning/provisioning-iphone.md
      - Provisioning with PC: provisioning/provisioning-pc-wifi.md
      - Provisioning with laptop with Bluetooth and Chrome : provisioning/provisioning-pc-ble.md
