site_name: thecrbox
repo_url: https://github.com/thecrbox/docs
repo_name: docs
site_url: https://thecrbox.github.io
theme:
    name: material
    custom_dir: overrides

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

plugins:
  - mkdocs-video
  - search
  - autorefs

extra_javascript:
  - javascripts/improv-loader.js
